export const Errors = {
  InternalError: "Внутренняя ошибка сервера",
  ValidationError: "Ошибка валидации данных",
  RecipeNotFound: "Рецепт не найден",
  Unauthorized: "Вы не авторизованы для выполнения этого действия.",
  Forbidden: "У вас нет прав для доступа к этому ресурсу.",
  NotFound: "Запрашиваемый ресурс не найден.",
  Conflict: "Конфликт данных.",
  BadRequest: "Некорректный запрос.",
  ServiceUnavailable: "Сервис временно недоступен. Попробуйте позже.",
  DatabaseError: "Ошибка базы данных.",
  InvalidCredentials: "Неверные учетные данные.",
  TokenExpired: "Ваш токен истек. Пожалуйста, войдите снова.",
  InsufficientPermissions: "Недостаточно прав для выполнения этого действия.",
  RateLimitExceeded: "Превышен лимит запросов. Пожалуйста, попробуйте позже.",
};
